server:
  port: 8021
spring:
  application:
    name: user-consumer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: wangbowen:${server.port}
  client:
    registerWithEureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
