spring:
  application:
    name: ares-register-center
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: true
    instance-id: register:${server.port}
---
server:
  port: 8761
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
    fetch-registry: false
    register-with-eureka: false
---
server:
  port: 8762
spring:
  profiles: test
eureka:
  instance:
    hostname: register-center-test
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 8763
spring:
  profiles: pro
eureka:
  instance:
    hostname: register-center-pro
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
